#config/routes.yalm
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


pag_principal:
    path: /
    controller: App\Controller\defaultController::defaults


buscar_productos:
    path: /buscar-productos
    controller: App\Controller\ProductoController::buscarProductos
    methods: ['GET', 'POST']

add_producto:
    path: /addProducto/{idProduct}
    controller: App\Controller\CarritoController::addProducto
    requirements:
        idProduct: \d+

app_carrito:
    path: /carrito/{id_carrito}
    controller: App\Controller\carritoController::index

buscarProducto:
    path: /buscarProducto
    controller: App\Controller\ProductController::search